# Generated by Django 6.0.2 on 2026-03-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_core',
            field=models.BooleanField(default=False, help_text='Whether this service is required platform infrastructure'),
        ),
        migrations.AddField(
            model_name='service',
            name='ui_path',
            field=models.CharField(blank=True, default='', help_text='Gateway-relative frontend path (e.g., /users, /rma, /fulfil)', max_length=100),
        ),
    ]
