# Generated by Django 6.0.2 on 2026-03-06 06:43

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_convert_role_values'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
